version: '3.8'
services:
  db:
    image: postgres:13
    container_name: packaging_db
    restart: always
    environment:
      POSTGRES_DB: packaging_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.db-data:/var/lib/postgresql/data

  go-backend:
    build:
      context: ./storage-backend/golang
    container_name: go_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/packaging_db"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data: